export const FACTURACION_EXPECTED_HEADERS = [
  "Año/Mes natural",
  "Centro",
  "Centro2",
  "Centro de Beneficio",
  "PSSR",
  "Motivo Pedido txt",
  "Pedido",
  "Marca",
  "CLIENTE",
  "FACTURA",
  "PSSR",
  "Fecha documento",
  "Fecha de facturación",
  "Piezas",
  "Venta Neta",
  "Gross Margin $",
  "repuestos",
  "Margen %",
  "Margen%",
  "Mano de obra",
  "Trabajos de Terceros",
  "Insumos",
  "Descuento",
  "Descuento%",
  "Año",
  "Mes",
  "% Repuestos",
  "% Mano de Obra",
  "Unidad",
  "Tipo Doc",
  "CAUSAL NC",
  "Año compra",
  "Mes compra",
  "Fecha de primera compra",
  "Primer mes de compra",
  "Esquema Servicio",
  "Tipo Facturacion",
  "Ultima Fact.",
  "Seguimiento",
] as const;

// Índice de cada columna dentro de la fila (0-based), documentado por nombre de campo del modelo Factura.
export const FACTURACION_COLUMN_INDEX = {
  anioMesNatural: 0,
  centro: 1,
  centro2: 2,
  centroBeneficio: 3,
  pssr: 4,
  motivoPedido: 5,
  pedido: 6,
  marca: 7,
  cliente: 8,
  factura: 9,
  fechaDocumento: 11,
  fechaFacturacion: 12,
  piezas: 13,
  ventaNeta: 14,
  grossMarginUsd: 15,
  repuestos: 16,
  margenPct: 17,
  manoObra: 19,
  trabajosTerceros: 20,
  insumos: 21,
  descuento: 22,
  descuentoPct: 23,
  anio: 24,
  mes: 25,
  pctRepuestos: 26,
  pctManoObra: 27,
  unidad: 28,
  tipoDoc: 29,
  causalNc: 30,
  anioCompra: 31,
  mesCompra: 32,
  fechaPrimeraCompra: 33,
  primerMesCompra: 34,
  esquemaServicio: 35,
  tipoFacturacion: 36,
  ultimaFactura: 37,
  seguimientoFecha: 38,
} as const;
